version: '3'
services:
  my-flask-app:
    container_name: flant5-container
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./cache:/root/.cache"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
